### ISSUE TITLE
upgrade dbal dependancy?

### ISSUE THREAD

**Issue by stokic** [artkonekt/address#7]
Hi,

is there any reason why   "doctrine/dbal": "~2.3, !=2.10.3" requirement is low? It conflicts with many newer packages that require dbla > 3.0... :/

**Comment by fulopattila122** [comment]
I can update it. In particular, <2.3 and 2.10.3 are known to have bugs, but I guess it'll work with v3.0+

**Comment by stokic** [comment]
that would be great, thanks :)

**Comment by fulopattila122** [comment]
Please upgrade konekt/address to v2.3.0

Thanks for the report!

**Comment by stokic** [comment]
sure thanks! btw konetk/user also has an older dbal 2.9 if I'm not mistaken...

**Comment by fulopattila122** [comment]
Thanks for mentioning it! Use 2.6.0 of konekt/user

Let me know if you find further delinquents :)

**Comment by stokic** [comment]
thanks :)
